#pragma once

// D3DConstants.h -- DirectX 7 SDK constant values the renderer passes to the
// device and surface methods (RenderInterfaces.h). The names are the SDK's own
// (d3dtypes.h, d3dcaps.h, ddraw.h); the VC98 headers stop at DirectX 5, so the
// values are written out here. Each value is tier 1 evidence only where the
// call site's method index identifies the SDK function receiving it (e.g.
// PCRenderTarget slot 8 forwards to device method 20, SetRenderState).

// D3DRENDERSTATETYPE (SetRenderState; PCRenderTarget slot 8 caches 300 of them).
enum D3DRenderState {
    D3DRENDERSTATE_TEXTUREHANDLE = 1,       // DirectX 6 legacy: 0 unbinds the texture
    D3DRENDERSTATE_ANTIALIAS = 2,
    D3DRENDERSTATE_TEXTUREPERSPECTIVE = 4,
    D3DRENDERSTATE_ZENABLE = 7,
    D3DRENDERSTATE_FILLMODE = 8,
    D3DRENDERSTATE_SHADEMODE = 9,
    D3DRENDERSTATE_ZWRITEENABLE = 14,
    D3DRENDERSTATE_ALPHATESTENABLE = 15,
    D3DRENDERSTATE_LASTPIXEL = 16,
    D3DRENDERSTATE_SRCBLEND = 19,
    D3DRENDERSTATE_DESTBLEND = 20,
    D3DRENDERSTATE_CULLMODE = 22,
    D3DRENDERSTATE_ZFUNC = 23,
    D3DRENDERSTATE_ALPHAREF = 24,
    D3DRENDERSTATE_ALPHAFUNC = 25,
    D3DRENDERSTATE_DITHERENABLE = 26,
    D3DRENDERSTATE_ALPHABLENDENABLE = 27,
    D3DRENDERSTATE_FOGENABLE = 28,
    D3DRENDERSTATE_SPECULARENABLE = 29,
    D3DRENDERSTATE_ZVISIBLE = 30,
    D3DRENDERSTATE_STIPPLEDALPHA = 33,
    D3DRENDERSTATE_FOGCOLOR = 34,
    D3DRENDERSTATE_FOGTABLEMODE = 35,
    D3DRENDERSTATE_FOGSTART = 36,
    D3DRENDERSTATE_FOGEND = 37,
    D3DRENDERSTATE_FOGDENSITY = 38,
    D3DRENDERSTATE_EDGEANTIALIAS = 40,
    D3DRENDERSTATE_COLORKEYENABLE = 41,
    D3DRENDERSTATE_ZBIAS = 47,
    D3DRENDERSTATE_RANGEFOGENABLE = 48,
    D3DRENDERSTATE_WRAP0 = 128,
    D3DRENDERSTATE_CLIPPING = 136,
    D3DRENDERSTATE_LIGHTING = 137,
    D3DRENDERSTATE_AMBIENT = 139,
    D3DRENDERSTATE_FOGVERTEXMODE = 140
};

// D3DCMPFUNC (ZFUNC, ALPHAFUNC).
enum D3DCmpFunc {
    D3DCMP_NEVER = 1,
    D3DCMP_LESS = 2,
    D3DCMP_EQUAL = 3,
    D3DCMP_LESSEQUAL = 4,
    D3DCMP_GREATER = 5,
    D3DCMP_NOTEQUAL = 6,
    D3DCMP_GREATEREQUAL = 7,
    D3DCMP_ALWAYS = 8
};

// D3DFILLMODE, D3DSHADEMODE, D3DCULL, D3DFOGMODE, D3DBLEND.
enum D3DFillMode { D3DFILL_POINT = 1, D3DFILL_WIREFRAME = 2, D3DFILL_SOLID = 3 };
enum D3DShadeMode { D3DSHADE_FLAT = 1, D3DSHADE_GOURAUD = 2, D3DSHADE_PHONG = 3 };
enum D3DCull { D3DCULL_NONE = 1, D3DCULL_CW = 2, D3DCULL_CCW = 3 };
enum D3DFogMode { D3DFOG_NONE = 0, D3DFOG_EXP = 1, D3DFOG_EXP2 = 2, D3DFOG_LINEAR = 3 };
enum D3DBlend {
    D3DBLEND_ZERO = 1,
    D3DBLEND_ONE = 2,
    D3DBLEND_SRCCOLOR = 3,
    D3DBLEND_INVSRCCOLOR = 4,
    D3DBLEND_SRCALPHA = 5,
    D3DBLEND_INVSRCALPHA = 6,
    D3DBLEND_DESTALPHA = 7,
    D3DBLEND_INVDESTALPHA = 8,
    D3DBLEND_DESTCOLOR = 9,
    D3DBLEND_INVDESTCOLOR = 10
};

// D3DTEXTURESTAGESTATETYPE and its D3DTEXTUREOP / D3DTA_* values
// (SetTextureStageState, device method 37).
enum D3DTextureStageState {
    D3DTSS_COLOROP = 1,
    D3DTSS_COLORARG1 = 2,
    D3DTSS_COLORARG2 = 3,
    D3DTSS_ALPHAOP = 4,
    D3DTSS_ALPHAARG1 = 5,
    D3DTSS_ALPHAARG2 = 6,
    D3DTSS_ADDRESS = 12,
    D3DTSS_MAGFILTER = 16,
    D3DTSS_MINFILTER = 17,
    D3DTSS_MIPFILTER = 18
};
enum D3DTextureOp {
    D3DTOP_DISABLE = 1,
    D3DTOP_SELECTARG1 = 2,
    D3DTOP_SELECTARG2 = 3,
    D3DTOP_MODULATE = 4,
    D3DTOP_MODULATE2X = 5,
    D3DTOP_MODULATE4X = 6,
    D3DTOP_ADD = 7,
    D3DTOP_BLENDTEXTUREALPHA = 13
};
enum D3DTextureArg { D3DTA_DIFFUSE = 0, D3DTA_CURRENT = 1, D3DTA_TEXTURE = 2 };
enum D3DTextureAddress { D3DTADDRESS_WRAP = 1, D3DTADDRESS_MIRROR = 2, D3DTADDRESS_CLAMP = 3 };
enum D3DTextureMagFilter { D3DTFG_POINT = 1, D3DTFG_LINEAR = 2 };
enum D3DTextureMinFilter { D3DTFN_POINT = 1, D3DTFN_LINEAR = 2 };
enum D3DTextureMipFilter { D3DTFP_NONE = 1, D3DTFP_POINT = 2, D3DTFP_LINEAR = 3 };

// D3DTRANSFORMSTATETYPE (SetTransform, device method 11).
enum D3DTransformState {
    D3DTRANSFORMSTATE_WORLD = 1,
    D3DTRANSFORMSTATE_VIEW = 2,
    D3DTRANSFORMSTATE_PROJECTION = 3
};

// D3DCLEAR_* flags (Clear, device method 10).
enum D3DClearFlags { D3DCLEAR_TARGET = 0x1, D3DCLEAR_ZBUFFER = 0x2, D3DCLEAR_STENCIL = 0x4 };

// D3DPRIMITIVETYPE (DrawPrimitive and friends).
enum D3DPrimitiveType {
    D3DPT_POINTLIST = 1,
    D3DPT_LINELIST = 2,
    D3DPT_LINESTRIP = 3,
    D3DPT_TRIANGLELIST = 4,
    D3DPT_TRIANGLESTRIP = 5,
    D3DPT_TRIANGLEFAN = 6
};

// Flexible vertex format bits.
enum D3DVertexFormat {
    D3DFVF_XYZ = 0x002,
    D3DFVF_XYZRHW = 0x004,
    D3DFVF_NORMAL = 0x010,
    D3DFVF_RESERVED1 = 0x020,
    D3DFVF_DIFFUSE = 0x040,
    D3DFVF_SPECULAR = 0x080,
    D3DFVF_TEX1 = 0x100,
    D3DFVF_VERTEX = 0x112,                  // XYZ | NORMAL | TEX1
    D3DFVF_LVERTEX = 0x1e2,                 // XYZ | RESERVED1 | DIFFUSE | SPECULAR | TEX1
    D3DFVF_TLVERTEX = 0x1c4                 // XYZRHW | DIFFUSE | SPECULAR | TEX1
};

// D3DPRIMCAPS bits (D3DDEVICEDESC7 dpcTriCaps, read by GetCaps).
enum D3DRasterCaps {
    D3DPRASTERCAPS_DITHER = 0x1,
    D3DPRASTERCAPS_FOGVERTEX = 0x80,
    D3DPRASTERCAPS_FOGTABLE = 0x100,
    D3DPRASTERCAPS_ANTIALIASSORTINDEPENDENT = 0x800,
    D3DPRASTERCAPS_FOGRANGE = 0x10000
};
enum D3DCmpCaps { D3DPCMPCAPS_GREATER = 0x10, D3DPCMPCAPS_NOTEQUAL = 0x20 };
enum D3DTextureCaps { D3DPTEXTURECAPS_TRANSPARENCY = 0x8 };
enum D3DTextureFilterCaps { D3DPTFILTERCAPS_LINEAR = 0x2, D3DPTFILTERCAPS_LINEARMIPLINEAR = 0x20 };
enum D3DDeviceCaps { D3DDEVCAPS_SEPARATETEXTUREMEMORIES = 0x4000 };

// DDSURFACEDESC2 flags, DDSCAPS bits, DDPIXELFORMAT flags and Lock flags.
enum DDSurfaceDescFlags {
    DDSD_CAPS = 0x1,
    DDSD_HEIGHT = 0x2,
    DDSD_WIDTH = 0x4,
    DDSD_PITCH = 0x8,
    DDSD_PIXELFORMAT = 0x1000,
    DDSD_MIPMAPCOUNT = 0x20000
};
enum DDSurfaceCaps {
    DDSCAPS_SYSTEMMEMORY = 0x800,
    DDSCAPS_TEXTURE = 0x1000,
    DDSCAPS_VIDEOMEMORY = 0x4000,
    DDSCAPS_ZBUFFER = 0x20000,
    DDSCAPS_LOCALVIDMEM = 0x10000000,
    DDSCAPS_NONLOCALVIDMEM = 0x20000000
};
enum DDPixelFormatFlags { DDPF_ZBUFFER = 0x400 };
enum DDLockFlags { DDLOCK_WAIT = 0x1, DDLOCK_READONLY = 0x10, DDLOCK_NOSYSLOCK = 0x800 };

// DirectDraw HRESULTs (PCTexMap.cpp's error reporter 0x004c86e0 names
// them in its string table).
#define DDERR_NOTFOUND 0x887600ff
#define DDERR_OUTOFVIDEOMEMORY 0x8876017c
