#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, os, subprocess, sys, tempfile
from pathlib import Path

CASES = [
    {
        'name': 'BaseObject::BaseObject constructor',
        'bindings': 'src/reconstructed/BaseObject.bindings.json',
        'source': 'src/reconstructed/BaseObject.cpp',
        'symbol': '??0BaseObject',
        'target_va': '0x00405120',
        'target_size': 16,
        'reason': 'constructor-body assignment preserves the retail vptr-before-field store order; vtable relocation is resolved',
    },
    {
        'name': 'BaseObject scalar deleting destructor',
        'bindings': 'src/reconstructed/BaseObject.bindings.json',
        'source': 'src/reconstructed/BaseObject.cpp',
        'symbol': '??_GBaseObject',
        'target_va': '0x00405130',
        'target_size': 30,
        'reason': 'canonical VC6 wrapper; CodeView supplies its length, both direct-call relocations are resolved',
    },
    {
        'name': 'BaseObject::~BaseObject destructor core',
        'bindings': 'src/reconstructed/BaseObject.bindings.json',
        'source': 'src/reconstructed/BaseObject.cpp',
        'symbol': '??1BaseObject',
        'target_va': '0x00405150',
        'target_size': 7,
        'reason': 'retail VC6 writes the BaseObject vptr in the destructor core while modern clang optimizes the empty body to ret',
    },
    {
        'name': 'BaseObject::Release',
        'source': 'src/reconstructed/BaseObject.cpp',
        'symbol': 'Release@BaseObject',
        'target_va': '0x00405170',
        'target_size': 32,
        'reason': 'local remaining count across virtual deletion; exact with VC6 /O2 without /G6',
    },
    {
        'name': 'UIControl::slot61 field difference',
        'source': 'samples/calibration/CompilerShapeProbe.cpp',
        'symbol': 'UnknownVirtualSlot61@UIControl',
        'target_va': '0x00470410',
        'target_size': 9,
        'reason': 'retail VC6 uses a second register for RHS; clang folds RHS into sub memory operand',
    },
    {
        'name': 'UIControl::slot62 field difference',
        'source': 'samples/calibration/CompilerShapeProbe.cpp',
        'symbol': 'UnknownVirtualSlot62@UIControl',
        'target_va': '0x00470420',
        'target_size': 9,
        'reason': 'same codegen discriminator with adjacent layout offsets',
    },
    {
        'name': 'UIStatic::slot30 return zero',
        'source': 'samples/calibration/CompilerShapeProbe.cpp',
        'symbol': 'UnknownVirtualSlot30@UIStatic',
        'target_va': '0x00478fe0',
        'target_size': 3,
        'reason': 'retail uses 33 C0; clang uses equivalent 31 C0, making this a tiny encoder fingerprint',
    },
    {
        'name': 'UIMultiState::slot34 indexed field +8',
        'source': 'samples/calibration/CompilerShapeProbe.cpp',
        'symbol': 'UnknownVirtualSlot34@UIMultiState',
        'target_va': '0x00478260',
        'target_size': 20,
        'reason': 'retail and clang agree on semantics/size but choose opposite equivalent SIB base/index ordering',
    },
    {
        'name': 'UIMultiState::slot35 indexed field +12',
        'source': 'samples/calibration/CompilerShapeProbe.cpp',
        'symbol': 'UnknownVirtualSlot35@UIMultiState',
        'target_va': '0x00478280',
        'target_size': 20,
        'reason': 'same VC6-vs-clang SIB discriminator; exposes 32-byte element stride',
    },
    {
        'name': 'UIMultiState::slot36 indexed field +28',
        'source': 'samples/calibration/CompilerShapeProbe.cpp',
        'symbol': 'UnknownVirtualSlot36@UIMultiState',
        'target_va': '0x004782a0',
        'target_size': 20,
        'reason': 'same VC6-vs-clang SIB discriminator with a third element field',
    },
    {
        'name': 'UIMultiState::slot37 indexed address +20',
        'source': 'samples/calibration/CompilerShapeProbe.cpp',
        'symbol': 'UnknownVirtualSlot37@UIMultiState',
        'target_va': '0x004782c0',
        'target_size': 20,
        'reason': 'retail VC6 uses LEA [eax+ecx+20], while clang separates add/add-immediate',
    },
    {
        'name': 'FollowCamera::slot63 zero camera preset',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': 'UnknownVirtualSlot63@FollowCamera',
        'target_va': '0x00466c90',
        'target_size': 21,
        'reason': 'retail VC6 zeros EAX once and fans it out to three fields; clang emits repeated immediate-zero stores',
    },
    {
        'name': 'Camera constructor',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/Camera.cpp',
        'symbol': '??0Camera@@QAE@H@Z',
        'target_va': '0x0042e340',
        'target_size': 402,
        'reason': '/GX frame; identity matrix copied from the returned pointer; vector temporaries; +0x214/+0x208 copied from +0x17c/+0x170',
    },
    {
        'name': 'IdentityMatrix 0x4a1410',
        'bindings': 'src/reconstructed/MatrixUtil.bindings.json',
        'source': 'src/reconstructed/MatrixUtil.cpp',
        'symbol': '?IdentityMatrix@@YA?AUMatrix4@@XZ',
        'target_va': '0x004a1410',
        'target_size': 71,
        'reason': 'nested 4x4 loop with (row == column) ? 1.0f : 0.0f; returned through the hidden pointer',
    },
    {
        'name': 'ZeroMatrix 0x4a13e0',
        'bindings': 'src/reconstructed/MatrixUtil.bindings.json',
        'source': 'src/reconstructed/MatrixUtil.cpp',
        'symbol': '?ZeroMatrix@@YA?AUMatrix4@@XZ',
        'target_va': '0x004a13e0',
        'target_size': 41,
        'reason': 'nested loop zeroing folds to rep stosd; returned through the hidden pointer',
    },
    {
        'name': 'ProjectionMatrix 0x4a1460',
        'bindings': 'src/reconstructed/MatrixUtil.bindings.json',
        'source': 'src/reconstructed/MatrixUtil.cpp',
        'symbol': '?ProjectionMatrix@@YA?AUMatrix4@@MMMM@Z',
        'target_va': '0x004a1460',
        'target_size': 156,
        'reason': 'cos/sin of fov*0.5 (double constant), cotangent, Q = 1/(1 - near/far)',
    },
    {
        'name': 'RotateZMatrix 0x4a17f0',
        'bindings': 'src/reconstructed/MatrixUtil.bindings.json',
        'source': 'src/reconstructed/MatrixUtil.cpp',
        'symbol': '?RotateZMatrix@@YA?AUMatrix4@@M@Z',
        'target_va': '0x004a17f0',
        'target_size': 106,
        'reason': 'identity with cos/sin in the upper 2x2',
    },
    {
        'name': 'MatrixMult 0x4a1860',
        'bindings': 'src/reconstructed/MatrixUtil.bindings.json',
        'source': 'src/reconstructed/MatrixUtil.cpp',
        'symbol': '?MatrixMult@@YA?AUMatrix4@@U1@0@Z',
        'target_va': '0x004a1860',
        'target_size': 123,
        'reason': 'matrices by value; only the operator() accessor form gives the retail fld/fmul operand order',
    },
    {
        'name': 'Camera 0x42e8e0 limit refresh',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/Camera.cpp',
        'symbol': '?UnknownFunction42e8e0@Camera@@QAEHXZ',
        'target_va': '0x0042e8e0',
        'target_size': 75,
        'reason': 'float != compares against the .rdata limits; 0x42e960 then virtual slot 28',
    },
    {
        'name': 'Camera 0x42e960 clamp',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/Camera.cpp',
        'symbol': '?UnknownFunction42e960@Camera@@QAEXMM@Z',
        'target_va': '0x0042e960',
        'target_size': 79,
        'reason': 'constant-first comparisons: ternary for +0x1bc, if/else for +0x1c0',
    },
    {
        'name': 'PCCamera slot27',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/PCCamera.cpp',
        'symbol': '?UnknownVirtualSlot27@PCCamera@@UAEXXZ',
        'target_va': '0x004beed0',
        'target_size': 19,
        'reason': 'owner helper 0x4c5d00, then tail call to 0x468880 on the 0x56e26c object',
    },
    {
        'name': 'Camera slot4 forward',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/Camera.cpp',
        'symbol': '?UnknownVirtualSlot4@Camera@@UAEXXZ',
        'target_va': '0x00499ad0',
        'target_size': 5,
        'reason': 'tail jump to GameObject slot 4; address shared by identical-code folding',
    },
    {
        'name': 'Camera slot8 attach',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/Camera.cpp',
        'symbol': '?UnknownVirtualSlot8@Camera@@UAEPAVGameObject@@PAX@Z',
        'target_va': '0x0042e500',
        'target_size': 65,
        'reason': 'GameObject slot 8, 0x42e550 gate with Release on failure, slot 28, owner notify on bit 0',
    },
    {
        'name': 'Camera slot14 return 1',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/Camera.cpp',
        'symbol': '?UnknownVirtualSlot14@Camera@@UAEHXZ',
        'target_va': '0x00467ae0',
        'target_size': 6,
        'reason': 'shared return-1 body',
    },
    {
        'name': 'Camera slot23 search fallback',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/Camera.cpp',
        'symbol': '?UnknownVirtualSlot23@Camera@@UAEHHH@Z',
        'target_va': '0x0042f090',
        'target_size': 71,
        'reason': 'GameObject slot 23, then cdecl 0x43caa0(0xb7, 0, a, 0x80000000) and slot 27',
    },
    {
        'name': 'FollowCamera slot34 raised target',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': '?UnknownVirtualSlot34@FollowCamera@@UAE?AUVector3@@H@Z',
        'target_va': '0x00464a40',
        'target_size': 63,
        'reason': 'Vector3 by hidden pointer; +0x2b4 with y + 3',
    },
    {
        'name': 'FollowCamera slot37 target',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': '?UnknownVirtualSlot37@FollowCamera@@UAE?AUVector3@@XZ',
        'target_va': '0x00464a10',
        'target_size': 37,
        'reason': 'named local copy of +0x2b4 returned by hidden pointer',
    },
    {
        'name': 'FollowCamera slot52 empty',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': '?UnknownVirtualSlot52@FollowCamera@@UAEXH@Z',
        'target_va': '0x00464e80',
        'target_size': 3,
        'reason': 'ret 4',
    },
    {
        'name': 'FollowCamera slot53 empty',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': '?UnknownVirtualSlot53@FollowCamera@@UAEXXZ',
        'target_va': '0x00464e90',
        'target_size': 1,
        'reason': 'ret; shared by slots 53, 54, 58-62',
    },
    {
        'name': 'FollowCamera slot55 interface call',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': '?UnknownVirtualSlot55@FollowCamera@@UAEXXZ',
        'target_va': '0x00464ea0',
        'target_size': 23,
        'reason': 'global 0x56e26c ->+0x14->+0x34 slot 5 (0x38, 0x3f, 0)',
    },
    {
        'name': 'FollowCamera slot56 interface call',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': '?UnknownVirtualSlot56@FollowCamera@@UAEXXZ',
        'target_va': '0x00464ec0',
        'target_size': 23,
        'reason': 'same chain with 0x2a',
    },
    {
        'name': 'FollowCamera slot75 state test',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': '?UnknownVirtualSlot75@FollowCamera@@UAEHXZ',
        'target_va': '0x00404fc0',
        'target_size': 25,
        'reason': 'state +0x244 is 5 or 2',
    },
    {
        'name': 'ShadowCamera constructor',
        'bindings': 'src/reconstructed/ShadowCamera.bindings.json',
        'source': 'src/reconstructed/ShadowCamera.cpp',
        'symbol': '??0ShadowCamera@@QAE@H@Z',
        'target_va': '0x004da520',
        'target_size': 25,
        'reason': 'PCCamera(flags), then the ShadowCamera vptr',
    },
    {
        'name': 'ShadowCamera slot19 return 0',
        'bindings': 'src/reconstructed/ShadowCamera.bindings.json',
        'source': 'src/reconstructed/ShadowCamera.cpp',
        'symbol': '?UnknownVirtualSlot19@ShadowCamera@@UAEHH@Z',
        'target_va': '0x004da550',
        'target_size': 5,
        'reason': 'xor eax,eax; ret 4',
    },
    {
        'name': 'ShadowCamera slot22 return 0',
        'bindings': 'src/reconstructed/ShadowCamera.bindings.json',
        'source': 'src/reconstructed/ShadowCamera.cpp',
        'symbol': '?UnknownVirtualSlot22@ShadowCamera@@UAEHHH@Z',
        'target_va': '0x004da560',
        'target_size': 5,
        'reason': 'xor eax,eax; ret 8',
    },
    {
        'name': 'FollowCamera destructor',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': '??1FollowCamera@@UAE@XZ',
        'target_va': '0x00463350',
        'target_size': 245,
        'reason': '/GX frame; null-checked deletes of +0x2e4 and the eight +0x27c..+0x298 values; ~Camera',
    },
    {
        'name': 'FollowCamera scalar deleting destructor',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': '??_GFollowCamera@@UAEPAXI@Z',
        'target_va': '0x00463120',
        'target_size': 30,
        'reason': 'canonical wrapper',
    },
    {
        'name': 'FollowCamera 0x463450 table entry',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': '?UnknownFunction463450@FollowCamera@@QAE_NHPBUVector3@@PBM1111@Z',
        'target_va': '0x00463450',
        'target_size': 201,
        'reason': 'bounds check wraps the body; five optional pointer-sourced fields in a 44-byte record',
    },
    {
        'name': 'FollowCamera slot40 seed table',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': '?UnknownVirtualSlot40@FollowCamera@@UAEXH@Z',
        'target_va': '0x004639f0',
        'target_size': 60,
        'reason': '0x463450(0, &target, 0...) then slot 38',
    },
    {
        'name': 'FollowCamera slot43 value feed',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': '?UnknownVirtualSlot43@FollowCamera@@UAEXABUVector3@@@Z',
        'target_va': '0x00464ee0',
        'target_size': 144,
        'reason': 'inlined UnknownFollowCameraValue::Set with FLT_MAX sentinel',
    },
    {
        'name': 'FollowCamera slot44 value feed',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': '?UnknownVirtualSlot44@FollowCamera@@UAEXABUVector3@@@Z',
        'target_va': '0x00464f70',
        'target_size': 144,
        'reason': 'same over +0x288..+0x290',
    },
    {
        'name': 'FollowCamera slot48 follow point',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': '?UnknownVirtualSlot48@FollowCamera@@UAE?AUVector3@@H_NH@Z',
        'target_va': '0x00464a80',
        'target_size': 175,
        'reason': 'single named result assigned per state',
    },
    {
        'name': 'FollowCamera slot73 ease distance',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': '?UnknownVirtualSlot73@FollowCamera@@UAEXABUVector3@@0M@Z',
        'target_va': '0x00463620',
        'target_size': 192,
        'reason': 'inline min function keeps the operand on the FPU stack; inlined Update',
    },
    {
        'name': 'VehicleCamera constructor',
        'bindings': 'src/reconstructed/VehicleCamera.bindings.json',
        'source': 'src/reconstructed/VehicleCamera.cpp',
        'symbol': '??0VehicleCamera@@QAE@H@Z',
        'target_va': '0x0052b920',
        'target_size': 137,
        'reason': 'FollowCamera(flags), flags and two copies of the 0x68a728 vector',
    },
    {
        'name': 'VehicleCamera destructor',
        'bindings': 'src/reconstructed/VehicleCamera.bindings.json',
        'source': 'src/reconstructed/VehicleCamera.cpp',
        'symbol': '??1VehicleCamera@@UAE@XZ',
        'target_va': '0x0052b9d0',
        'target_size': 11,
        'reason': 'explicit empty destructor: vptr store, jump to ~FollowCamera',
    },
    {
        'name': 'VehicleCamera scalar deleting destructor',
        'bindings': 'src/reconstructed/VehicleCamera.bindings.json',
        'source': 'src/reconstructed/VehicleCamera.cpp',
        'symbol': '??_GVehicleCamera@@UAEPAXI@Z',
        'target_va': '0x0052b9b0',
        'target_size': 30,
        'reason': 'canonical wrapper',
    },
    {
        'name': 'VehicleCamera slot39',
        'bindings': 'src/reconstructed/VehicleCamera.bindings.json',
        'source': 'src/reconstructed/VehicleCamera.cpp',
        'symbol': '?UnknownVirtualSlot39@VehicleCamera@@UAEMXZ',
        'target_va': '0x0052cbd0',
        'target_size': 41,
        'reason': 'returns vehicle +0x45c; +0x23c += pi when +0x464',
    },
    {
        'name': 'VehicleCamera slot50',
        'bindings': 'src/reconstructed/VehicleCamera.bindings.json',
        'source': 'src/reconstructed/VehicleCamera.cpp',
        'symbol': '?UnknownVirtualSlot50@VehicleCamera@@UAE?AUVector3@@XZ',
        'target_va': '0x0052cb80',
        'target_size': 73,
        'reason': 'vehicle part position 0 raised by 5',
    },
    {
        'name': 'VehicleCamera slot51',
        'bindings': 'src/reconstructed/VehicleCamera.bindings.json',
        'source': 'src/reconstructed/VehicleCamera.cpp',
        'symbol': '?UnknownVirtualSlot51@VehicleCamera@@UAEMXZ',
        'target_va': '0x0052cec0',
        'target_size': 10,
        'reason': 'vehicle +0x48',
    },
    {
        'name': 'VehicleCamera slot67 preset',
        'bindings': 'src/reconstructed/VehicleCamera.bindings.json',
        'source': 'src/reconstructed/VehicleCamera.cpp',
        'symbol': '?UnknownVirtualSlot67@VehicleCamera@@UAEXXZ',
        'target_va': '0x0052bfa0',
        'target_size': 76,
        'reason': 'ternary distance through the FPU; 85.0 tail-duplicated',
    },
    {
        'name': 'VehicleCamera slot72',
        'bindings': 'src/reconstructed/VehicleCamera.bindings.json',
        'source': 'src/reconstructed/VehicleCamera.cpp',
        'symbol': '?UnknownVirtualSlot72@VehicleCamera@@UAEXXZ',
        'target_va': '0x0052bff0',
        'target_size': 62,
        'reason': 'hold, reset or FollowCamera slot 72 tail call',
    },
    {
        'name': 'VehicleCamera slot74 (inline)',
        'bindings': 'src/reconstructed/VehicleCamera.bindings.json',
        'source': 'src/reconstructed/VehicleCamera.cpp',
        'symbol': '?UnknownVirtualSlot74@VehicleCamera@@UAE_NXZ',
        'target_va': '0x00417490',
        'target_size': 31,
        'reason': 'named bool local gives setne al',
    },
    {
        'name': 'VehicleCamera slot75',
        'bindings': 'src/reconstructed/VehicleCamera.bindings.json',
        'source': 'src/reconstructed/VehicleCamera.cpp',
        'symbol': '?UnknownVirtualSlot75@VehicleCamera@@UAEHXZ',
        'target_va': '0x0052d010',
        'target_size': 58,
        'reason': 'inline FollowCamera slot 75 || two-return inline helper (materialised sete)',
    },
    {
        'name': 'BikeCamera constructor',
        'bindings': 'src/reconstructed/BikeCamera.bindings.json',
        'source': 'src/reconstructed/BikeCamera.cpp',
        'symbol': '??0BikeCamera@@QAE@H@Z',
        'target_va': '0x00416e20',
        'target_size': 35,
        'reason': 'VehicleCamera(flags), vptr, +0x3b0 = 0',
    },
    {
        'name': 'BikeCamera destructor',
        'bindings': 'src/reconstructed/BikeCamera.bindings.json',
        'source': 'src/reconstructed/BikeCamera.cpp',
        'symbol': '??1BikeCamera@@UAE@XZ',
        'target_va': '0x00416e70',
        'target_size': 11,
        'reason': 'explicit empty destructor',
    },
    {
        'name': 'BikeCamera scalar deleting destructor',
        'bindings': 'src/reconstructed/BikeCamera.bindings.json',
        'source': 'src/reconstructed/BikeCamera.cpp',
        'symbol': '??_GBikeCamera@@UAEPAXI@Z',
        'target_va': '0x00416e50',
        'target_size': 30,
        'reason': 'canonical wrapper',
    },
    {
        'name': 'BikeCamera slot37',
        'bindings': 'src/reconstructed/BikeCamera.bindings.json',
        'source': 'src/reconstructed/BikeCamera.cpp',
        'symbol': '?UnknownVirtualSlot37@BikeCamera@@UAE?AUVector3@@XZ',
        'target_va': '0x00416fb0',
        'target_size': 153,
        'reason': '"Head" lookup as its own statement; 0.38 lerp toward the target',
    },
    {
        'name': 'BikeCamera slot50',
        'bindings': 'src/reconstructed/BikeCamera.bindings.json',
        'source': 'src/reconstructed/BikeCamera.cpp',
        'symbol': '?UnknownVirtualSlot50@BikeCamera@@UAE?AUVector3@@XZ',
        'target_va': '0x00417290',
        'target_size': 77,
        'reason': 'rider "Head" position',
    },
    {
        'name': 'BikeCamera slot51',
        'bindings': 'src/reconstructed/BikeCamera.bindings.json',
        'source': 'src/reconstructed/BikeCamera.cpp',
        'symbol': '?UnknownVirtualSlot51@BikeCamera@@UAEMXZ',
        'target_va': '0x00417340',
        'target_size': 13,
        'reason': 'bike +0x58 * +0x48',
    },
    {
        'name': 'BikeCamera slot53',
        'bindings': 'src/reconstructed/BikeCamera.bindings.json',
        'source': 'src/reconstructed/BikeCamera.cpp',
        'symbol': '?UnknownVirtualSlot53@BikeCamera@@UAEXXZ',
        'target_va': '0x004172e0',
        'target_size': 45,
        'reason': '0x4444e0 on bike part and rider',
    },
    {
        'name': 'BikeCamera slot54',
        'bindings': 'src/reconstructed/BikeCamera.bindings.json',
        'source': 'src/reconstructed/BikeCamera.cpp',
        'symbol': '?UnknownVirtualSlot54@BikeCamera@@UAEXXZ',
        'target_va': '0x00417310',
        'target_size': 45,
        'reason': '0x4fdb50 on bike part and rider',
    },
    {
        'name': 'BikeCamera slot75',
        'bindings': 'src/reconstructed/BikeCamera.bindings.json',
        'source': 'src/reconstructed/BikeCamera.cpp',
        'symbol': '?UnknownVirtualSlot75@BikeCamera@@UAEHXZ',
        'target_va': '0x004174b0',
        'target_size': 72,
        'reason': 'inline FollowCamera slot 75 plus bike state tests',
    },
    {
        'name': 'GameObject constructor',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': '??0GameObject@@QAE@H@Z',
        'target_va': '0x00468ca0',
        'target_size': 149,
        'reason': '/GX frame for the BaseObject subobject; one merged bitfield store; DebugMalloc(1, __FILE__, 31); class-name append 0x469ce0',
    },
    {
        'name': 'GameObject scalar deleting destructor',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': '??_GGameObject@@UAEPAXI@Z',
        'target_va': '0x00468d40',
        'target_size': 30,
        'reason': 'canonical wrapper: ~GameObject 0x468d60 then operator delete 0x4a30c0',
    },
    {
        'name': 'GameObject destructor',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': '??1GameObject@@UAE@XZ',
        'target_va': '0x00468d60',
        'target_size': 97,
        'reason': '/GX frame; frees field_0x28 via operator delete(p, __FILE__, 40); ~BaseObject 0x405150',
    },
    {
        'name': 'GameObject 0x469680 sibling release',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': '?UnknownFunction469680@GameObject@@QAEHXZ',
        'target_va': '0x00469680',
        'target_size': 58,
        'reason': 'recurses along next siblings, detaches, then virtual Release',
    },
    {
        'name': 'GameObject 0x469ce0 class-name append',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': '?UnknownFunction469ce0@GameObject@@QAEXPAV1@@Z',
        'target_va': '0x00469ce0',
        'target_size': 201,
        'reason': 'typeid(*object).name() minus "class ", DebugRealloc(__FILE__, 1163), inline strlen/strcat',
    },
    {
        'name': 'GameObject::slot5 set bits + slot 7',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': '?UnknownVirtualSlot5@GameObject@@UAEXXZ',
        'target_va': '0x004690b0',
        'target_size': 13,
        'reason': 'two bitfield sets merge into or al,3; tail jmp to slot 7',
    },
    {
        'name': 'GameObject::slot21 child walk',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': '?UnknownVirtualSlot21@GameObject@@UAEHH@Z',
        'target_va': '0x00469c40',
        'target_size': 60,
        'reason': 'ungated walk, bit 0 and not bit 3, first nonzero wins',
    },
    {
        'name': 'GameObject::slot24 child walk',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': '?UnknownVirtualSlot24@GameObject@@UAEHHHHHH@Z',
        'target_va': '0x00469620',
        'target_size': 94,
        'reason': 'gated by field_0x20 & 0x800, child bit 1, five forwarded arguments',
    },
    {
        'name': 'GameObject::slot25 owner propagation',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': '?UnknownVirtualSlot25@GameObject@@UAEHPAX@Z',
        'target_va': '0x00469720',
        'target_size': 68,
        'reason': 'next sibling read before the call; stores value in field_0x18',
    },
    {
        'name': 'GameObject::Release override',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'Release@GameObject',
        'target_va': '0x004696c0',
        'target_size': 81,
        'reason': 'blocked by global 0x65b548; first child 0x469680; sibling/parent unlink; BaseObject::Release',
    },
    {
        'name': 'GameObject::slot4 clear bits + slot 6',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot4@GameObject',
        'target_va': '0x004690a0',
        'target_size': 13,
        'reason': 'clears field_0x25 bits 0-1 then tail-calls slot 6',
    },
    {
        'name': 'GameObject::slot6 child walk',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot6@GameObject',
        'target_va': '0x00469050',
        'target_size': 30,
        'reason': 'calls slot 6 on each child without bit 3',
    },
    {
        'name': 'GameObject::slot7 child walk',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot7@GameObject',
        'target_va': '0x00469070',
        'target_size': 35,
        'reason': 'calls slot 7 on each child with bit 0 and without bit 3',
    },
    {
        'name': 'GameObject::slot8 set +0x18',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot8@GameObject',
        'target_va': '0x004692f0',
        'target_size': 12,
        'reason': 'stores the argument at +0x18 and returns this',
    },
    {
        'name': 'GameObject::slot9 gated walk',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot9@GameObject',
        'target_va': '0x00469430',
        'target_size': 65,
        'reason': 'field_0x20 bit 0; children with bit 0 and without bits 2/3',
    },
    {
        'name': 'GameObject::slot10 gated walk + owner part',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot10@GameObject',
        'target_va': '0x004693d0',
        'target_size': 94,
        'reason': 'field_0x20 bit 1; after each child, owner+4 part slot 4 when its +0x70 bit 2 is set',
    },
    {
        'name': 'GameObject::slot11 return one',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot11@GameObject',
        'target_va': '0x004da540',
        'target_size': 8,
        'reason': 'shared return-1 body (identical-code folding)',
    },
    {
        'name': 'GameObject::slot12 gated walk',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot12@GameObject',
        'target_va': '0x00469300',
        'target_size': 48,
        'reason': 'field_0x20 bit 12',
    },
    {
        'name': 'GameObject::slot13 gated walk',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot13@GameObject',
        'target_va': '0x00469330',
        'target_size': 47,
        'reason': 'field_0x20 bit 2',
    },
    {
        'name': 'GameObject::slot14 gated walk, stop on 0',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot14@GameObject',
        'target_va': '0x00469360',
        'target_size': 55,
        'reason': 'field_0x20 bit 3; returns 0 at the first failing child',
    },
    {
        'name': 'GameObject::slot15 gated walk',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot15@GameObject',
        'target_va': '0x004693a0',
        'target_size': 47,
        'reason': 'field_0x20 bit 4',
    },
    {
        'name': 'GameObject::slot16 set bit 2 + gated walk',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot16@GameObject',
        'target_va': '0x00469480',
        'target_size': 74,
        'reason': 'bitfield-style store of the argument low bit, then field_0x20 bit 5 walk',
    },
    {
        'name': 'GameObject::slot17 gated walk',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot17@GameObject',
        'target_va': '0x00469500',
        'target_size': 42,
        'reason': 'field_0x20 bit 6; children without bit 3',
    },
    {
        'name': 'GameObject::slot18 gated walk',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot18@GameObject',
        'target_va': '0x004694d0',
        'target_size': 42,
        'reason': 'field_0x20 bit 7; children without bit 3',
    },
    {
        'name': 'GameObject::slot19 gated search',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot19@GameObject',
        'target_va': '0x00469530',
        'target_size': 68,
        'reason': 'field_0x20 bit 8; returns 1 at the first child returning nonzero',
    },
    {
        'name': 'GameObject::slot20 search',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot20@GameObject',
        'target_va': '0x00469c00',
        'target_size': 60,
        'reason': 'ungated; returns 1 at the first child returning nonzero',
    },
    {
        'name': 'GameObject::slot22 gated search',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot22@GameObject',
        'target_va': '0x00469580',
        'target_size': 76,
        'reason': 'field_0x20 bit 9; two arguments',
    },
    {
        'name': 'GameObject::slot23 gated search',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot23@GameObject',
        'target_va': '0x004695d0',
        'target_size': 76,
        'reason': 'field_0x20 bit 10; two arguments',
    },
    {
        'name': 'GameObject::slot26 walk + set bit 3',
        'bindings': 'src/reconstructed/GameObject.bindings.json',
        'source': 'src/reconstructed/GameObject.cpp',
        'symbol': 'UnknownVirtualSlot26@GameObject',
        'target_va': '0x004692c0',
        'target_size': 36,
        'reason': 'slot 26 on every child, then sets its own bit 3',
    },
    {
        'name': 'Camera::~Camera destructor core',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/Camera.cpp',
        'symbol': '??1Camera',
        'target_va': '0x0042f020',
        'target_size': 37,
        'reason': 'Camera vptr, fclose(+0x1e4) when set, GameObject destructor; fclose is LIBCMT mt fclose.obj per the CRT atlas',
    },
    {
        'name': 'Camera scalar deleting destructor',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/Camera.cpp',
        'symbol': '??_GCamera',
        'target_va': '0x0042e4e0',
        'target_size': 30,
        'reason': 'canonical VC6 wrapper around 0x42f020 and operator delete 0x4a30c0',
    },
    {
        'name': 'PCCamera::PCCamera constructor',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/PCCamera.cpp',
        'symbol': '??0PCCamera',
        'target_va': '0x004bed80',
        'target_size': 25,
        'reason': 'forwards its argument to Camera(int) at 0x42e340, then the PCCamera vptr',
    },
    {
        'name': 'PCCamera compiler-generated destructor',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/PCCamera.cpp',
        'symbol': '??1PCCamera',
        'target_va': '0x004624d0',
        'target_size': 5,
        'reason': 'implicit destructor: tail jump to ~Camera with no PCCamera vptr store (the only PCCamera vptr write is in the constructor)',
    },
    {
        'name': 'PCCamera scalar deleting destructor',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/PCCamera.cpp',
        'symbol': '??_GPCCamera',
        'target_va': '0x004beda0',
        'target_size': 30,
        'reason': 'wrapper shared by PCCamera and ShadowCamera slot 0',
    },
    {
        'name': 'Camera::slot5 base call + owner sync',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/Camera.cpp',
        'symbol': 'UnknownVirtualSlot5@Camera',
        'target_va': '0x0042f050',
        'target_size': 32,
        'reason': 'calls GameObject slot 5 and the owner helper 0x4e8cf0, then stores owner+0x14 plus one at +0x1d0',
    },
    {
        'name': 'Camera::slot13 rectangle + refresh',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/Camera.cpp',
        'symbol': 'UnknownVirtualSlot13@Camera',
        'target_va': '0x0042e630',
        'target_size': 92,
        'reason': 'optional x/y/width/height rectangle to owner slot 12, then the non-virtual 0x42e8e0; /G6 schedules differently',
    },
    {
        'name': 'Camera::slot18 base call + counter',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/Camera.cpp',
        'symbol': 'UnknownVirtualSlot18@Camera',
        'target_va': '0x0042f070',
        'target_size': 28,
        'reason': 'GameObject slot 18 then +0x1d0 = owner+0x14 plus one; /G6 schedules differently',
    },
    {
        'name': 'Camera::slot30 64-byte block +0x2c',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/Camera.cpp',
        'symbol': 'UnknownVirtualSlot30@Camera',
        'target_va': '0x0042edd0',
        'target_size': 26,
        'reason': '16-dword struct copy (rep movsd) returning 1; /G6 orders the return load differently',
    },
    {
        'name': 'Camera::slot31 64-byte block +0xac',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/Camera.cpp',
        'symbol': 'UnknownVirtualSlot31@Camera',
        'target_va': '0x0042edf0',
        'target_size': 29,
        'reason': '16-dword struct copy returning 1',
    },
    {
        'name': 'Camera::slot32 64-byte block +0x6c',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/Camera.cpp',
        'symbol': 'UnknownVirtualSlot32@Camera',
        'target_va': '0x0042ee10',
        'target_size': 26,
        'reason': '16-dword struct copy returning 1',
    },
    {
        'name': 'PCCamera::slot13 re-send view/projection',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/PCCamera.cpp',
        'symbol': 'UnknownVirtualSlot13@PCCamera',
        'target_va': '0x004bee80',
        'target_size': 65,
        'reason': 'Camera slot 13, then interface method 11 with kinds 2 and 3 when owner+0x08 is this camera',
    },
    {
        'name': 'PCCamera::slot30 block + interface kind 1',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/PCCamera.cpp',
        'symbol': 'UnknownVirtualSlot30@PCCamera',
        'target_va': '0x004bedc0',
        'target_size': 54,
        'reason': 'Camera slot 30, then optional interface method 11 (COM-style __stdcall) with kind 1',
    },
    {
        'name': 'PCCamera::slot31 block + interface kind 2',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/PCCamera.cpp',
        'symbol': 'UnknownVirtualSlot31@PCCamera',
        'target_va': '0x004bee00',
        'target_size': 54,
        'reason': 'Camera slot 31, then optional interface method 11 with kind 2',
    },
    {
        'name': 'PCCamera::slot32 block + interface kind 3',
        'bindings': 'src/reconstructed/Camera.bindings.json',
        'source': 'src/reconstructed/PCCamera.cpp',
        'symbol': 'UnknownVirtualSlot32@PCCamera',
        'target_va': '0x004bee40',
        'target_size': 54,
        'reason': 'Camera slot 32, then optional interface method 11 with kind 3',
    },
    {
        'name': 'FollowCamera::slot68 distance-derived +0x258 parameter',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': 'UnknownVirtualSlot68@FollowCamera',
        'target_va': '0x00466d50',
        'target_size': 241,
        'reason': 'x87 distance/clamp path; every float constant binding is checked against the retail literal and the call resolves to 0x460b50',
    },
    {
        'name': 'FollowCamera::slot69 cached 12-byte aggregate',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': 'UnknownVirtualSlot69@FollowCamera',
        'target_va': '0x00466a80',
        'target_size': 65,
        'reason': 'hidden 12-byte return-buffer ABI plus three-dword cache copy; clang /GS- is 64 bytes but schedules copy/registers differently',
    },
    {
        'name': 'FollowCamera::slot70 mode/state toggle',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': 'UnknownVirtualSlot70@FollowCamera',
        'target_va': '0x00467040',
        'target_size': 101,
        'reason': 'strongly reconstructed state/save/restore flow; modern clang chooses different register allocation and branch shape',
    },
    {
        'name': 'FollowCamera::slot71 state dispatcher',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': 'UnknownVirtualSlot71@FollowCamera',
        'target_va': '0x00466e50',
        'target_size': 192,
        'reason': 'state 0-4 virtual dispatch plus camera-preset snapshot is strongly reconstructed; clang /GS- emits 151 bytes with different VC6-era switch/register scheduling. Extent is 171 code bytes + 1 alignment NOP + the 5-entry jump table (retail entries 0x466e77..0x466eb3 all point into this function)',
    },
    {
        'name': 'FollowCamera::slot72 cyclic state-list advance',
        'bindings': 'src/reconstructed/FollowCamera.bindings.json',
        'source': 'src/reconstructed/FollowCamera.cpp',
        'symbol': 'UnknownVirtualSlot72@FollowCamera',
        'target_va': '0x00466fb0',
        'target_size': 62,
        'reason': 'retail keeps explicit increment/store/compare/wrap; modern P6 clang uses CMOV and Pentium clang still folds more aggressively',
    },
]

def main():
    ap=argparse.ArgumentParser(description='Run compiler-calibration targets. Non-exact results are data, not failure.')
    ap.add_argument('--exe',default='work/game/mcm2.exe')
    ap.add_argument('--compiler',choices=['clang-cl','vc6'],default='clang-cl')
    ap.add_argument('--vc6-root',default=os.environ.get('VC6_ROOT'))
    ap.add_argument('--profile')
    args=ap.parse_args()
    rows=[]
    with tempfile.TemporaryDirectory() as td:
        # Each source is compiled once per run; cases sharing a file reuse it.
        compiled={}
        for i,c in enumerate(CASES):
            if c['source'] not in compiled:
                obj=Path(td)/f'cal{len(compiled)}.obj'
                cmd=[sys.executable,'tools/compile.py',c['source'],'-o',str(obj),'--compiler',args.compiler]
                if args.profile: cmd += ['--profile',args.profile]
                if args.compiler=='vc6':
                    if not args.vc6_root: raise SystemExit('VC6 run requested: set VC6_ROOT or pass --vc6-root')
                    cmd += ['--vc6-root',args.vc6_root]
                cr=subprocess.run(cmd,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
                compiled[c['source']]=(obj,cr.returncode,cr.stdout)
            obj,rc,out=compiled[c['source']]
            if rc:
                rows.append({**c,'compile_error':out}); continue
            match_cmd=[sys.executable,'tools/match.py','--exe',args.exe,'--target-va',c['target_va'],'--target-size',str(c['target_size']),'--obj',str(obj),'--symbol',c['symbol'],'--json']
            if c.get('bindings'): match_cmd += ['--bindings',c['bindings']]
            mr=subprocess.run(match_cmd,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
            try: result=json.loads(mr.stdout)
            except Exception: result={'match_error':mr.stdout}
            rows.append({**c,'compiler':args.compiler,'result':result})
    print(json.dumps(rows,indent=2))

if __name__=='__main__': main()
